/* 
 * Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data
 *
 * The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.
 *
 * OpenAPI spec version: 2021-10-28
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = spApiCsharpApp.swaggerClient.Client.SwaggerDateConverter;

namespace spApiCsharpApp.swaggerClient.Model.DirectFulfillmentSandboxData
{
    /// <summary>
    /// The set of test case data returned in response to the test data request.
    /// </summary>
    [DataContract]
    public partial class TestCaseData :  IEquatable<TestCaseData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestCaseData" /> class.
        /// </summary>
        /// <param name="scenarios">Set of use cases that describes the possible test scenarios..</param>
        public TestCaseData(List<Scenario> scenarios = default(List<Scenario>))
        {
            this.Scenarios = scenarios;
        }
        
        /// <summary>
        /// Set of use cases that describes the possible test scenarios.
        /// </summary>
        /// <value>Set of use cases that describes the possible test scenarios.</value>
        [DataMember(Name="scenarios", EmitDefaultValue=false)]
        public List<Scenario> Scenarios { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TestCaseData {\n");
            sb.Append("  Scenarios: ").Append(Scenarios).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TestCaseData);
        }

        /// <summary>
        /// Returns true if TestCaseData instances are equal
        /// </summary>
        /// <param name="input">Instance of TestCaseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TestCaseData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Scenarios == input.Scenarios ||
                    this.Scenarios != null &&
                    this.Scenarios.SequenceEqual(input.Scenarios)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Scenarios != null)
                    hashCode = hashCode * 59 + this.Scenarios.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
