version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/code-recipes/java/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "composer"
    directory: "/code-recipes/php/"
    schedule:
      interval: "weekly"
