# coding: utf-8

"""
    Amazon Shipping API

    The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.  # noqa: E501

    OpenAPI spec version: v2
    Contact: swa-api-core@amazon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetCarrierAccountFormInputsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'linkable_carriers_list': 'LinkableCarriersList'
    }

    attribute_map = {
        'linkable_carriers_list': 'linkableCarriersList'
    }

    def __init__(self, linkable_carriers_list=None):  # noqa: E501
        """GetCarrierAccountFormInputsResponse - a model defined in Swagger"""  # noqa: E501
        self._linkable_carriers_list = None
        self.discriminator = None
        if linkable_carriers_list is not None:
            self.linkable_carriers_list = linkable_carriers_list

    @property
    def linkable_carriers_list(self):
        """Gets the linkable_carriers_list of this GetCarrierAccountFormInputsResponse.  # noqa: E501


        :return: The linkable_carriers_list of this GetCarrierAccountFormInputsResponse.  # noqa: E501
        :rtype: LinkableCarriersList
        """
        return self._linkable_carriers_list

    @linkable_carriers_list.setter
    def linkable_carriers_list(self, linkable_carriers_list):
        """Sets the linkable_carriers_list of this GetCarrierAccountFormInputsResponse.


        :param linkable_carriers_list: The linkable_carriers_list of this GetCarrierAccountFormInputsResponse.  # noqa: E501
        :type: LinkableCarriersList
        """

        self._linkable_carriers_list = linkable_carriers_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetCarrierAccountFormInputsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetCarrierAccountFormInputsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
