/*
 * Selling Partner API for Notifications
 * The Selling Partner API for Notifications lets you subscribe to notifications that are relevant to a selling partner's business. Using this API you can create a destination to receive notifications, subscribe to notifications, delete notification subscriptions, and more.  For more information, see the [Notifications Use Case Guide](doc:notifications-api-v1-use-case-guide).
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.notifications;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The information required to create an Amazon Simple Queue Service (Amazon SQS) queue destination.
 */
@ApiModel(description = "The information required to create an Amazon Simple Queue Service (Amazon SQS) queue destination.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-07T17:07:51.757+01:00")
public class SqsResource {
  @SerializedName("arn")
  private String arn = null;

  public SqsResource arn(String arn) {
    this.arn = arn;
    return this;
  }

   /**
   * The Amazon Resource Name (ARN) associated with the SQS queue.
   * @return arn
  **/
  @ApiModelProperty(required = true, value = "The Amazon Resource Name (ARN) associated with the SQS queue.")
  public String getArn() {
    return arn;
  }

  public void setArn(String arn) {
    this.arn = arn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SqsResource sqsResource = (SqsResource) o;
    return Objects.equals(this.arn, sqsResource.arn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SqsResource {\n");
    
    sb.append("    arn: ").append(toIndentedString(arn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

