/*
 * Selling Partner API for Notifications
 * The Selling Partner API for Notifications lets you subscribe to notifications that are relevant to a selling partner's business. Using this API you can create a destination to receive notifications, subscribe to notifications, delete notification subscriptions, and more.  For more information, see the [Notifications Use Case Guide](doc:notifications-api-v1-use-case-guide).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

import { ApiClient } from "../ApiClient.js";
import { AggregationSettings } from "./AggregationSettings.js";

/**
 * The AggregationFilter model module.
 * @module notifications/js-client.notifications.model/AggregationFilter
 * @version v1
 */
export class AggregationFilter {
  /**
   * Constructs a new <code>AggregationFilter</code>.
   * Use this filter to select the aggregation time period at which to send notifications (e.g. limit to one notification every five minutes for high frequency notifications).
   * @alias module:notifications/js-client.notifications.model/AggregationFilter
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>AggregationFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:notifications/js-client.notifications.model/AggregationFilter} obj Optional instance to populate.
   * @return {module:notifications/js-client.notifications.model/AggregationFilter} The populated <code>AggregationFilter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AggregationFilter();
      if (data.hasOwnProperty("aggregationSettings"))
        obj.aggregationSettings = AggregationSettings.constructFromObject(
          data["aggregationSettings"],
        );
    }
    return obj;
  }
}

/**
 * @member {module:notifications/js-client.notifications.model/AggregationSettings} aggregationSettings
 */
AggregationFilter.prototype.aggregationSettings = undefined;
