/*
 * Selling Partner API for Notifications
 * The Selling Partner API for Notifications lets you subscribe to notifications that are relevant to a selling partner's business. Using this API you can create a destination to receive notifications, subscribe to notifications, delete notification subscriptions, and more.  For more information, see the [Notifications Use Case Guide](doc:notifications-api-v1-use-case-guide).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

import { ApiClient } from "../ApiClient.js";

/**
 * The EventBridgeResource model module.
 * @module notifications/js-client.notifications.model/EventBridgeResource
 * @version v1
 */
export class EventBridgeResource {
  /**
   * Constructs a new <code>EventBridgeResource</code>.
   * Represents an Amazon EventBridge destination.
   * @alias module:notifications/js-client.notifications.model/EventBridgeResource
   * @class
   * @param name {String} The name of the partner event source associated with the destination.
   * @param region {String} The AWS region in which you receive the notifications. For AWS regions that are supported in Amazon EventBridge, see https://docs.aws.amazon.com/general/latest/gr/ev.html.
   * @param accountId {String} The identifier for the AWS account that is responsible for charges related to receiving notifications.
   */
  constructor(name, region, accountId) {
    this.name = name;
    this.region = region;
    this.accountId = accountId;
  }

  /**
   * Constructs a <code>EventBridgeResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:notifications/js-client.notifications.model/EventBridgeResource} obj Optional instance to populate.
   * @return {module:notifications/js-client.notifications.model/EventBridgeResource} The populated <code>EventBridgeResource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventBridgeResource();
      if (data.hasOwnProperty("name"))
        obj.name = ApiClient.convertToType(data["name"], "String");
      if (data.hasOwnProperty("region"))
        obj.region = ApiClient.convertToType(data["region"], "String");
      if (data.hasOwnProperty("accountId"))
        obj.accountId = ApiClient.convertToType(data["accountId"], "String");
    }
    return obj;
  }
}

/**
 * The name of the partner event source associated with the destination.
 * @member {String} name
 */
EventBridgeResource.prototype.name = undefined;

/**
 * The AWS region in which you receive the notifications. For AWS regions that are supported in Amazon EventBridge, see https://docs.aws.amazon.com/general/latest/gr/ev.html.
 * @member {String} region
 */
EventBridgeResource.prototype.region = undefined;

/**
 * The identifier for the AWS account that is responsible for charges related to receiving notifications.
 * @member {String} accountId
 */
EventBridgeResource.prototype.accountId = undefined;
