# Region configuration
NA_REGION_CODE = "NA"
SP_API_NA_ENDPOINT = "https://sellingpartnerapi-na.amazon.com"
EU_REGION_CODE = "EU"
SP_API_EU_ENDPOINT = "https://sellingpartnerapi-eu.amazon.com"
FE_REGION_CODE = "FE"
SP_API_FE_ENDPOINT = "https://sellingpartnerapi-fe.amazon.com"


# Sandbox configuration
SANDBOX_REGION_CODE = "SANDBOX"
SP_API_NA_SANDBOX_ENDPOINT = "https://sandbox.sellingpartnerapi-na.amazon.com"


# Region to endpoint mapping
VALID_SP_API_REGION_CONFIG = {
    NA_REGION_CODE: SP_API_NA_ENDPOINT,
    EU_REGION_CODE: SP_API_EU_ENDPOINT,
    FE_REGION_CODE: SP_API_FE_ENDPOINT,
    SANDBOX_REGION_CODE: SP_API_NA_SANDBOX_ENDPOINT
}


# Login With Amazon Configuration
LWA_ENDPOINT = "https://api.amazon.com/auth/o2/token"


# Lambda Environment Variables
SP_API_APP_CREDENTIALS_SECRET_ARN_ENV_VARIABLE = "SP_API_APP_CREDENTIALS_SECRET_ARN"


# Generic Lambda Input Parameters
REGION_CODE_KEY_NAME = "RegionCode"
REFRESH_TOKEN_KEY_NAME = "RefreshToken"
SECRETS_MANAGER_KEY_NAME = "secretsmanager"


# API Type
DATA_KIOSK_API_TYPE = "datakiosk"
NOTIFICATIONS_API_TYPE = "notifications"


# Lambda Constants
QUERY_CODE_KEY_NAME = "Query"
QUERY_ID_KEY_NAME = "QueryId"


# Notification Attributes
NOTIFICATION_TYPE_DK = "DATA_KIOSK_QUERY_PROCESSING_FINISHED"
LWA_NOTIFICATIONS_SCOPE = "sellingpartnerapi::notifications"
NOTIFICATION_KEY_NOTIFICATION_TYPE = "notificationType"
SUB_NOTIFICATION_KEY_NOTIFICATION_TYPE = "NotificationType"
NOTIFICATION_KEY_QUERY_ID = "queryId"
NOTIFICATION_KEY_QUERY = "query"
NOTIFICATION_KEY_PROCESSING_STATUS = "processingStatus"
NOTIFICATION_KEY_DATA_DOCUMENT_ID = "dataDocumentId"
NOTIFICATION_KEY_ERROR_DOCUMENT_ID = "errorDocumentId"
NOTIFICATION_KEY_ACCOUNT_ID = "accountId"
NOTIFICATION_KEY_FATAL_PROCESSING = "Fatal"

# State Machine Attributes
STATE_MACHINE_ARN_ENV_VARIABLE = "STATE_MACHINE_ARN"
STATE_MACHINE_KEY_DOCUMENT_ID = "documentId"
STATE_MACHINE_KEY_PROCESSING_STATUS = "processingStatus"
STATE_MACHINE_KEY_DOCUMENT = "document"
STATE_MACHINE_KEY_QUERY = "query"
STATE_MACHINE_KEY_QUERY_ID = "queryId"
STATE_MACHINE_KEY_ACCOUNT_ID = "accountId"


# AWS Attributes
AWS_STEP_FUNCTIONS_CLIENT_NAME = "stepfunctions"
AWS_STEP_FUNCTIONS_EXECUTION_ARN_NAME = "executionArn"


# Env Variables
REFRESH_TOKEN_ARN_ENV_VARIABLE = "REFRESH_TOKEN"
REGION_CODE_ARN_ENV_VARIABLE = "REGION_CODE"
SQS_QUEUE_ARN_ENV_VARIABLE = "SQS_QUEUE_ARN"
DATAKIOSK_DOCUMENTS_S3_BUCKET_NAME_ENV_VARIABLE = "DATAKIOSK_DOCUMENTS_S3_BUCKET_NAME"
QUERY_ITEMS_TABLE_NAME_ENV_VARIABLE = "QUERY_ITEMS_TABLE_NAME"

