/*
 * Selling Partner API for Listings Items
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](doc:listings-items-api-v2021-08-01-use-case-guide).
 *
 * OpenAPI spec version: 2021-08-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

import { ApiClient } from "../ApiClient.js";
import { PatchOperation } from "./PatchOperation.js";

/**
 * The ListingsItemPatchRequest model module.
 * @module listingsItems_2021-08-01/js-client.listingsItems_2021-08-01.model/ListingsItemPatchRequest
 * @version 2021-08-01
 */
export class ListingsItemPatchRequest {
  /**
   * Constructs a new <code>ListingsItemPatchRequest</code>.
   * The request body schema for the patchListingsItem operation.
   * @alias module:listingsItems_2021-08-01/js-client.listingsItems_2021-08-01.model/ListingsItemPatchRequest
   * @class
   * @param productType {String} The Amazon product type of the listings item.
   * @param patches {Array.<module:listingsItems_2021-08-01/js-client.listingsItems_2021-08-01.model/PatchOperation>} One or more JSON Patch operations to perform on the listings item.
   */
  constructor(productType, patches) {
    this.productType = productType;
    this.patches = patches;
  }

  /**
   * Constructs a <code>ListingsItemPatchRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:listingsItems_2021-08-01/js-client.listingsItems_2021-08-01.model/ListingsItemPatchRequest} obj Optional instance to populate.
   * @return {module:listingsItems_2021-08-01/js-client.listingsItems_2021-08-01.model/ListingsItemPatchRequest} The populated <code>ListingsItemPatchRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListingsItemPatchRequest();
      if (data.hasOwnProperty("productType"))
        obj.productType = ApiClient.convertToType(
          data["productType"],
          "String",
        );
      if (data.hasOwnProperty("patches"))
        obj.patches = ApiClient.convertToType(data["patches"], [
          PatchOperation,
        ]);
    }
    return obj;
  }
}

/**
 * The Amazon product type of the listings item.
 * @member {String} productType
 */
ListingsItemPatchRequest.prototype.productType = undefined;

/**
 * One or more JSON Patch operations to perform on the listings item.
 * @member {Array.<module:listingsItems_2021-08-01/js-client.listingsItems_2021-08-01.model/PatchOperation>} patches
 */
ListingsItemPatchRequest.prototype.patches = undefined;
