# LABEL FORMAT
LABEL_FORMAT_PDF = "PDF"
LABEL_SIZE = {"width": 4, "length": 6, "unit": "INCH"}
PRINT_OPTIONS = {"includePackingSlip": False}
PAGE_LAYOUT = "DEFAULT"
REQ_DOCUMENT_TYPES = ["LABEL"]
DPI = 300  # Possible values "300" or "203"

REQ_DOC_FORMAT = "PDF"
REQ_DOC_SIZE_WIDTH = 10
REQ_DOC_SIZE_LENGTH = 10
REQ_DOC_SIZE_UNIT = "CENTIMETER"

REQ_DOC_NEED_JOINING = False

# SHIPMENT DETAILS
SHIPMENT_TYPE = "FORWARD"
CHANNEL_TYPE = "AMAZON"
SERVICE_SELECTION = {"serviceId": ["std-us-swa-mfn"]}  # This is the only valid serviceId value in US
PACKAGES_INSURED_VALUE = {"value": 1, "unit": "USD"}

# ITEM DETAILS
ITEM_DESCRIPTION = "Item Description"

# VALUE ADDED SERVICES
VALUE_ADDED_SERVICE = "SIGNATURE_CONFIRMATION"
