from enum import Enum

# Region configuration
NA_REGION_CODE = "NA"
SP_API_NA_ENDPOINT = "https://sellingpartnerapi-na.amazon.com"
EU_REGION_CODE = "EU"
SP_API_EU_ENDPOINT = "https://sellingpartnerapi-eu.amazon.com"
FE_REGION_CODE = "FE"
SP_API_FE_ENDPOINT = "https://sellingpartnerapi-fe.amazon.com"


# Region to Endpoint mapping
VALID_SP_API_REGION_CONFIG = {
    NA_REGION_CODE: SP_API_NA_ENDPOINT,
    EU_REGION_CODE: SP_API_EU_ENDPOINT,
    FE_REGION_CODE: SP_API_FE_ENDPOINT,
}


# MarketplaceId to Region mapping
MARKETPLACE_ID_TO_REGION_CODE_MAPPING = {
    "A2EUQ1WTGCTBG2": NA_REGION_CODE,   # CA
    "ATVPDKIKX0DER": NA_REGION_CODE,    # US
    "A1AM78C64UM0Y8": NA_REGION_CODE,   # MX
    "A2Q3Y263D00KWC": NA_REGION_CODE,   # BR
    "A1RKKUPIHCS9HS": EU_REGION_CODE,   # ES
    "A1F83G8C2ARO7P": EU_REGION_CODE,   # UK
    "A13V1IB3VIYZZH": EU_REGION_CODE,   # FR
    "AMEN7PMS3EDWL": EU_REGION_CODE,    # BE
    "A1805IZSGTT6HS": EU_REGION_CODE,   # NL
    "A1PA6795UKMFR9": EU_REGION_CODE,   # DE
    "APJ6JRA9NG5V4": EU_REGION_CODE,    # IT
    "A2NODRKZP88ZB9": EU_REGION_CODE,   # SE
    "AE08WJ6YKNBMC": EU_REGION_CODE,    # ZA
    "A1C3SOZRARQ6R3": EU_REGION_CODE,   # PL
    "ARBP9OOSHTCHU": EU_REGION_CODE,    # EG
    "A33AVAJ2PDY3EV": EU_REGION_CODE,   # TR
    "A17E79C6D8DWNP": EU_REGION_CODE,   # SA
    "A2VIGQ35RCS4UG": EU_REGION_CODE,   # AE
    "A21TJRUUN4KGV": EU_REGION_CODE,    # IN
    "A19VAU5U5O7RUS": FE_REGION_CODE,   # SG
    "A39IBJ37TRP1C6": FE_REGION_CODE,   # AU
    "A1VC38T7YXB528": FE_REGION_CODE,   # JP
}


# Login With Amazon Configuration
LWA_ENDPOINT = "https://api.amazon.com/auth/o2/token"


# Lambda Environment Variables
SP_API_APP_CREDENTIALS_SECRET_ARN_ENV_VARIABLE = "SP_API_APP_CREDENTIALS_SECRET_ARN"
SELLER_ITEMS_TABLE_NAME_ENV_VARIABLE = "SELLER_ITEMS_TABLE_NAME"


# Generic Lambda Input Parameters
REGION_CODE_KEY_NAME = "RegionCode"
REFRESH_TOKEN_KEY_NAME = "RefreshToken"


# State Machine Attributes
STATE_MACHINE_ARN_ENV_VARIABLE = "STATE_MACHINE_ARN"
STATE_MACHINE_KEY_REFRESH_TOKEN = "refreshToken"
STATE_MACHINE_KEY_REGION_CODE = "regionCode"
STATE_MACHINE_KEY_ASIN = "asin"
STATE_MACHINE_KEY_CREDENTIALS = "credentials"
STATE_MACHINE_KEY_OFFER_TYPE = "offerChangeType"
STATE_MACHINE_KEY_BUY_BOX = "buyBox"
STATE_MACHINE_KEY_BUY_BOX_CONDITION = "condition"
STATE_MACHINE_KEY_BUY_BOX_PRICE = "price"
STATE_MACHINE_KEY_SELLER = "seller"
STATE_MACHINE_KEY_SELLER_ID = "sellerId"
STATE_MACHINE_KEY_OFFERS = "offers"
STATE_MACHINE_KEY_SHIPPING_PRICE = "shippingPrice"
STATE_MACHINE_KEY_LISTING_PRICE = "listingPrice"
STATE_MACHINE_KEY_IS_BUY_BOX_WINNER = "isBuyBoxWinner"
STATE_MACHINE_KEY_MARKETPLACE_ID = "marketplaceId"
STATE_MACHINE_KEY_IS_FULFILLED_BY_AMAZON ="isFulfilledByAmazon"


# AWS Attributes
AWS_STEP_FUNCTIONS_CLIENT_NAME = "stepfunctions"
AWS_STEP_FUNCTIONS_ARN_NAME = "executionArn"
REFRESH_TOKEN_ARN_ENV_VARIABLE = "REFRESH_TOKEN"
REGION_CODE_ARN_ENV_VARIABLE = "REGION_CODE"
SQS_QUEUE_ARN_ENV_VARIABLE = "SQS_QUEUE_ARN"
SECRETS_MANAGER_CLIENT_NAME = "secretsmanager"


# Notifications Configurations
NOTIFICATION_TYPE_AOC = "ANY_OFFER_CHANGED"
LWA_NOTIFICATIONS_SCOPE = "sellingpartnerapi::notifications"


# Notification Attributes
NOTIFICATION_KEY_NOTIFICATION_TYPE = "NotificationType"
NOTIFICATION_KEY_OFFER_CHANGE_TYPE = "OfferChangeType"
NOTIFICATION_KEY_OFFER_CHANGE_TRIGGER = "OfferChangeTrigger"
NOTIFICATION_KEY_ASIN = "ASIN"
NOTIFICATION_KEY_MARKETPLACE_ID = "MarketplaceId"
NOTIFICATION_KEY_SUMMARY = "Summary"
NOTIFICATION_KEY_BUY_BOX_PRICES = "BuyBoxPrices"
NOTIFICATION_BUY_BOX_PRICES_ITEM = 0
NOTIFICATION_KEY_ITEM_CONDITION = "Condition"
NOTIFICATION_KEY_LANDED_PRICE = "LandedPrice"
NOTIFICATION_KEY_OFFERS = "Offers"
NOTIFICATION_KEY_SELLER_ID = "SellerId"
NOTIFICATION_KEY_LISTING_PRICE = "ListingPrice"
NOTIFICATION_KEY_SHIPPING_PRICE = "Shipping"
NOTIFICATION_KEY_IS_BUY_BOX_WINNER = "IsBuyBoxWinner"
NOTIFICATION_KEY_IS_FULFILLED_BY_AMAZON = "IsFulfilledByAmazon"


# API Type
LISTINGS_API_TYPE = "listings"
PRICING_API_TYPE = "pricing"
NOTIFICATIONS_API_TYPE = "notifications"


# DynamoDB Attributes
SELLER_TABLE_HASH_KEY_NAME = "SKU"
AWS_DYNAMO_DB_CLIENT_KEY_NAME = "dynamodb"
SELLER_TABLE_NAME_ENV_VARIABLE = "SELLER_ITEMS_TABLE_NAME"
SELLER_TABLE_ASIN_KEY_NAME = "ASIN"
SELLER_TABLE_CONDITION_KEY_NAME = "Condition"
SELLER_TABLE_MARKETPLACE_KEY_NAME = "MarketplaceId"
SELLER_TABLE_SELLER_ID_KEY_NAME = "SellerId"
SELLER_TABLE_IS_FULFILLED_BY_AMAZON_KEY_NAME = "IsFulfilledByAmazon"
SELLER_TABLE_THRESHOLD_KEY_NAME = "MinThreshold"
SELLER_TABLE_PRICE_CHANGE_RULE_KEY_NAME = "PriceChangeRule"
SELLER_TABLE_PRICE_CHANGE_AMOUNT_KEY_NAME = "PriceChangeRuleAmount"


# Price Change Enum Value
class PriceChangeRule(Enum):
    PERCENTAGE = "PERCENTAGE"
    FIXED = "FIXED"