/*
 * Selling Partner API for Feeds
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * OpenAPI spec version: 2021-06-30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

import { ApiClient } from "../ApiClient.js";

/**
 * The FeedOptions model module.
 * @module feeds_2021-06-30/js-client.feeds_2021-06-30.model/FeedOptions
 * @version 2021-06-30
 */
export class FeedOptions {
  /**
   * Constructs a new <code>FeedOptions</code>.
   * Additional options to control the feed. These vary by feed type.
   * @alias module:feeds_2021-06-30/js-client.feeds_2021-06-30.model/FeedOptions
   * @class
   * @extends Object
   */
  constructor() {}

  /**
   * Constructs a <code>FeedOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:feeds_2021-06-30/js-client.feeds_2021-06-30.model/FeedOptions} obj Optional instance to populate.
   * @return {module:feeds_2021-06-30/js-client.feeds_2021-06-30.model/FeedOptions} The populated <code>FeedOptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FeedOptions();
      ApiClient.constructFromObject(data, obj, "String");
    }
    return obj;
  }
}
