/*
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-04-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

import { ApiClient } from "./ApiClient.js";
import { BrandRefinement } from "./js-client.catalogItems_2022-04-01.model/BrandRefinement.js";
import { ClassificationRefinement } from "./js-client.catalogItems_2022-04-01.model/ClassificationRefinement.js";
import { Dimension } from "./js-client.catalogItems_2022-04-01.model/Dimension.js";
import { Dimensions } from "./js-client.catalogItems_2022-04-01.model/Dimensions.js";
import { Error } from "./js-client.catalogItems_2022-04-01.model/Error.js";
import { ErrorList } from "./js-client.catalogItems_2022-04-01.model/ErrorList.js";
import { Item } from "./js-client.catalogItems_2022-04-01.model/Item.js";
import { ItemAsin } from "./js-client.catalogItems_2022-04-01.model/ItemAsin.js";
import { ItemAttributes } from "./js-client.catalogItems_2022-04-01.model/ItemAttributes.js";
import { ItemBrowseClassification } from "./js-client.catalogItems_2022-04-01.model/ItemBrowseClassification.js";
import { ItemClassificationSalesRank } from "./js-client.catalogItems_2022-04-01.model/ItemClassificationSalesRank.js";
import { ItemContributor } from "./js-client.catalogItems_2022-04-01.model/ItemContributor.js";
import { ItemContributorRole } from "./js-client.catalogItems_2022-04-01.model/ItemContributorRole.js";
import { ItemDimensions } from "./js-client.catalogItems_2022-04-01.model/ItemDimensions.js";
import { ItemDimensionsByMarketplace } from "./js-client.catalogItems_2022-04-01.model/ItemDimensionsByMarketplace.js";
import { ItemDisplayGroupSalesRank } from "./js-client.catalogItems_2022-04-01.model/ItemDisplayGroupSalesRank.js";
import { ItemIdentifier } from "./js-client.catalogItems_2022-04-01.model/ItemIdentifier.js";
import { ItemIdentifiers } from "./js-client.catalogItems_2022-04-01.model/ItemIdentifiers.js";
import { ItemIdentifiersByMarketplace } from "./js-client.catalogItems_2022-04-01.model/ItemIdentifiersByMarketplace.js";
import { ItemImage } from "./js-client.catalogItems_2022-04-01.model/ItemImage.js";
import { ItemImages } from "./js-client.catalogItems_2022-04-01.model/ItemImages.js";
import { ItemImagesByMarketplace } from "./js-client.catalogItems_2022-04-01.model/ItemImagesByMarketplace.js";
import { ItemProductTypeByMarketplace } from "./js-client.catalogItems_2022-04-01.model/ItemProductTypeByMarketplace.js";
import { ItemProductTypes } from "./js-client.catalogItems_2022-04-01.model/ItemProductTypes.js";
import { ItemRelationship } from "./js-client.catalogItems_2022-04-01.model/ItemRelationship.js";
import { ItemRelationships } from "./js-client.catalogItems_2022-04-01.model/ItemRelationships.js";
import { ItemRelationshipsByMarketplace } from "./js-client.catalogItems_2022-04-01.model/ItemRelationshipsByMarketplace.js";
import { ItemSalesRanks } from "./js-client.catalogItems_2022-04-01.model/ItemSalesRanks.js";
import { ItemSalesRanksByMarketplace } from "./js-client.catalogItems_2022-04-01.model/ItemSalesRanksByMarketplace.js";
import { ItemSearchResults } from "./js-client.catalogItems_2022-04-01.model/ItemSearchResults.js";
import { ItemSummaries } from "./js-client.catalogItems_2022-04-01.model/ItemSummaries.js";
import { ItemSummaryByMarketplace } from "./js-client.catalogItems_2022-04-01.model/ItemSummaryByMarketplace.js";
import { ItemVariationTheme } from "./js-client.catalogItems_2022-04-01.model/ItemVariationTheme.js";
import { ItemVendorDetails } from "./js-client.catalogItems_2022-04-01.model/ItemVendorDetails.js";
import { ItemVendorDetailsByMarketplace } from "./js-client.catalogItems_2022-04-01.model/ItemVendorDetailsByMarketplace.js";
import { ItemVendorDetailsCategory } from "./js-client.catalogItems_2022-04-01.model/ItemVendorDetailsCategory.js";
import { Pagination } from "./js-client.catalogItems_2022-04-01.model/Pagination.js";
import { Refinements } from "./js-client.catalogItems_2022-04-01.model/Refinements.js";
import { CatalogApi } from "./js-client.catalogItems_2022-04-01.api/CatalogApi.js";

/**
 * The_Selling_Partner_API_for_Catalog_Items_provides_programmatic_access_to_information_about_items_in_the_Amazon_catalog_For_more_information_refer_to_the__Catalog_Items_API_Use_Case_Guide_doccatalog_items_api_v2022_04_01_use_case_guide_.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var SellingPartnerApiForCatalogItems = require('catalogItems_2022-04-01/index'); // See note below*.
 * var xxxSvc = new SellingPartnerApiForCatalogItems.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new SellingPartnerApiForCatalogItems.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['catalogItems_2022-04-01/index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new SellingPartnerApiForCatalogItems.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new SellingPartnerApiForCatalogItems.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module catalogItems_2022-04-01/index
 * @version 2022-04-01
 */
export {
  /**
   * The ApiClient constructor.
   * @property {module:catalogItems_2022-04-01/ApiClient}
   */
  ApiClient,

  /**
   * The BrandRefinement model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/BrandRefinement}
   */
  BrandRefinement,

  /**
   * The ClassificationRefinement model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ClassificationRefinement}
   */
  ClassificationRefinement,

  /**
   * The Dimension model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/Dimension}
   */
  Dimension,

  /**
   * The Dimensions model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/Dimensions}
   */
  Dimensions,

  /**
   * The Error model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/Error}
   */
  Error,

  /**
   * The ErrorList model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ErrorList}
   */
  ErrorList,

  /**
   * The Item model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/Item}
   */
  Item,

  /**
   * The ItemAsin model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemAsin}
   */
  ItemAsin,

  /**
   * The ItemAttributes model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemAttributes}
   */
  ItemAttributes,

  /**
   * The ItemBrowseClassification model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemBrowseClassification}
   */
  ItemBrowseClassification,

  /**
   * The ItemClassificationSalesRank model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemClassificationSalesRank}
   */
  ItemClassificationSalesRank,

  /**
   * The ItemContributor model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemContributor}
   */
  ItemContributor,

  /**
   * The ItemContributorRole model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemContributorRole}
   */
  ItemContributorRole,

  /**
   * The ItemDimensions model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemDimensions}
   */
  ItemDimensions,

  /**
   * The ItemDimensionsByMarketplace model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemDimensionsByMarketplace}
   */
  ItemDimensionsByMarketplace,

  /**
   * The ItemDisplayGroupSalesRank model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemDisplayGroupSalesRank}
   */
  ItemDisplayGroupSalesRank,

  /**
   * The ItemIdentifier model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemIdentifier}
   */
  ItemIdentifier,

  /**
   * The ItemIdentifiers model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemIdentifiers}
   */
  ItemIdentifiers,

  /**
   * The ItemIdentifiersByMarketplace model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemIdentifiersByMarketplace}
   */
  ItemIdentifiersByMarketplace,

  /**
   * The ItemImage model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemImage}
   */
  ItemImage,

  /**
   * The ItemImages model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemImages}
   */
  ItemImages,

  /**
   * The ItemImagesByMarketplace model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemImagesByMarketplace}
   */
  ItemImagesByMarketplace,

  /**
   * The ItemProductTypeByMarketplace model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemProductTypeByMarketplace}
   */
  ItemProductTypeByMarketplace,

  /**
   * The ItemProductTypes model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemProductTypes}
   */
  ItemProductTypes,

  /**
   * The ItemRelationship model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemRelationship}
   */
  ItemRelationship,

  /**
   * The ItemRelationships model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemRelationships}
   */
  ItemRelationships,

  /**
   * The ItemRelationshipsByMarketplace model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemRelationshipsByMarketplace}
   */
  ItemRelationshipsByMarketplace,

  /**
   * The ItemSalesRanks model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemSalesRanks}
   */
  ItemSalesRanks,

  /**
   * The ItemSalesRanksByMarketplace model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemSalesRanksByMarketplace}
   */
  ItemSalesRanksByMarketplace,

  /**
   * The ItemSearchResults model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemSearchResults}
   */
  ItemSearchResults,

  /**
   * The ItemSummaries model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemSummaries}
   */
  ItemSummaries,

  /**
   * The ItemSummaryByMarketplace model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemSummaryByMarketplace}
   */
  ItemSummaryByMarketplace,

  /**
   * The ItemVariationTheme model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemVariationTheme}
   */
  ItemVariationTheme,

  /**
   * The ItemVendorDetails model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemVendorDetails}
   */
  ItemVendorDetails,

  /**
   * The ItemVendorDetailsByMarketplace model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemVendorDetailsByMarketplace}
   */
  ItemVendorDetailsByMarketplace,

  /**
   * The ItemVendorDetailsCategory model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/ItemVendorDetailsCategory}
   */
  ItemVendorDetailsCategory,

  /**
   * The Pagination model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/Pagination}
   */
  Pagination,

  /**
   * The Refinements model constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.model/Refinements}
   */
  Refinements,

  /**
   * The CatalogApi service constructor.
   * @property {module:catalogItems_2022-04-01/js-client.catalogItems_2022-04-01.api/CatalogApi}
   */
  CatalogApi,
};
